// data.js — Catálogo de TU Lugar Fit
// Editá precios, nombres o agregá productos acá; el resto del sitio no necesita tocarse.

const CONFIG = {
  nombreNegocio: "TU Lugar Fit",
  eslogan: "Equipamiento para entrenar en casa, en el gym o al aire libre",
  whatsappPrincipal: "5491138153616",
  whatsappSecundario: "5491155959484",
  whatsappPrincipalDisplay: "11 3815-3616",
  whatsappSecundarioDisplay: "11 5595-9484",
  instagram: "tu.lugarfit",
  instagramUrl: "https://instagram.com/tu.lugarfit",
  avisoPrecios: "Precios sujetos a modificación sin previo aviso.",
};

// Orden de categorías tal como deben mostrarse los filtros/chips
const CATEGORIAS = [
  "Tobilleras",
  "Bandas",
  "Pesas rusas",
  "Barras",
  "Boxeo",
  "Coordinación y equilibrio",
  "Colchonetas y mats",
  "Funcional / Crossfit",
  "Body pump y discos",
  "Mancuernas",
  "Fitness",
  "Artículos",
  "Pelotas",
  "Otros",
  "Pileta",
];

const PRODUCTOS = [
  {
    id: 1,
    nombre: "Tobilleras de 1 kg (el par)",
    categoria: "Tobilleras",
    precio: 11400,
    unidad: "par",
    imagen: "img/productos/001-tobilleras-de-1-kg-el-par.jpeg",
  },
  {
    id: 2,
    nombre: "Tobilleras de 2 kg (el par)",
    categoria: "Tobilleras",
    precio: 13700,
    unidad: "par",
    imagen: "img/productos/002-tobilleras-de-2-kg-el-par.jpeg",
  },
  {
    id: 3,
    nombre: "Tobilleras de 3 kg (el par)",
    categoria: "Tobilleras",
    precio: 15200,
    unidad: "par",
    imagen: "img/productos/003-tobilleras-de-3-kg-el-par.jpeg",
  },
  {
    id: 4,
    nombre: "Tobilleras de 4 kg (el par)",
    categoria: "Tobilleras",
    precio: 18000,
    unidad: "par",
    imagen: "img/productos/004-tobilleras-de-4-kg-el-par.jpeg",
  },
  {
    id: 5,
    nombre: "Tobilleras de 5 kg (el par)",
    categoria: "Tobilleras",
    precio: 21000,
    unidad: "par",
    imagen: "img/productos/005-tobilleras-de-5-kg-el-par.jpeg",
  },
  {
    id: 6,
    nombre: "Banda larga Thera, int. baja",
    categoria: "Bandas",
    precio: 9000,
    unidad: null,
    imagen: "img/productos/006-banda-larga-thera-int-baja.jpeg",
  },
  {
    id: 7,
    nombre: "Banda larga Thera, int. media",
    categoria: "Bandas",
    precio: 10000,
    unidad: null,
    imagen: "img/productos/007-banda-larga-thera-int-media.jpeg",
  },
  {
    id: 8,
    nombre: "Banda larga Thera, int. alta",
    categoria: "Bandas",
    precio: 11000,
    unidad: null,
    imagen: "img/productos/008-banda-larga-thera-int-alta.jpeg",
  },
  {
    id: 9,
    nombre: "Banda circular latex KRV int media-fuerte",
    categoria: "Bandas",
    precio: 6500,
    unidad: null,
    imagen: "img/productos/009-banda-circular-latex-krv-int-media-fuerte.jpeg",
  },
  {
    id: 10,
    nombre: "Kit bandas tela 8 cm de ancho (baja/media/alta)",
    categoria: "Bandas",
    precio: 22000,
    unidad: null,
    imagen: "img/productos/010-kit-bandas-tela-8-cm-de-ancho-baja-media-alta.jpeg",
  },
  {
    id: 11,
    nombre: "Kit banda de tela 5 cm de ancho( baja/media/alta)",
    categoria: "Bandas",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/011-kit-banda-de-tela-5-cm-de-ancho-baja-media-alta.jpeg",
  },
  {
    id: 12,
    nombre: "Banda de tela x unidad",
    categoria: "Bandas",
    precio: 5000,
    unidad: null,
    imagen: "img/productos/012-banda-de-tela-x-unidad.jpeg",
  },
  {
    id: 13,
    nombre: "Kit bandas latex x 3 KRV",
    categoria: "Bandas",
    precio: 14200,
    unidad: null,
    imagen: "img/productos/013-kit-bandas-latex-x-3-krv.jpeg",
  },
  {
    id: 14,
    nombre: "Kit bandas latex x5 intensidades",
    categoria: "Bandas",
    precio: 16000,
    unidad: null,
    imagen: "img/productos/014-kit-bandas-latex-x5-intensidades.jpeg",
  },
  {
    id: 15,
    nombre: "Banda circular premium 8cm de ancho",
    categoria: "Bandas",
    precio: 10500,
    unidad: null,
    imagen: "img/productos/015-banda-circular-premium-8cm-de-ancho.jpeg",
  },
  {
    id: 16,
    nombre: "Banda dominada 0,6mm",
    categoria: "Bandas",
    precio: 10000,
    unidad: null,
    imagen: "img/productos/016-banda-dominada-0-6mm.jpeg",
  },
  {
    id: 17,
    nombre: "Banda asistencia dominada 13 mm",
    categoria: "Bandas",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/017-banda-asistencia-dominada-13-mm.jpeg",
  },
  {
    id: 18,
    nombre: "Banda asistencia dominada 20 mm",
    categoria: "Bandas",
    precio: 19000,
    unidad: null,
    imagen: "img/productos/018-banda-asistencia-dominada-20-mm.jpeg",
  },
  {
    id: 19,
    nombre: "Banda asistencia dominada 32mm",
    categoria: "Bandas",
    precio: 21000,
    unidad: null,
    imagen: "img/productos/019-banda-asistencia-dominada-32mm.jpeg",
  },
  {
    id: 20,
    nombre: "Banda asistencia dominada 45 mm",
    categoria: "Bandas",
    precio: 29000,
    unidad: null,
    imagen: "img/productos/020-banda-asistencia-dominada-45-mm.jpeg",
  },
  {
    id: 21,
    nombre: "Kit de bandas dominadas x 5",
    categoria: "Bandas",
    precio: 50000,
    unidad: null,
    imagen: "img/productos/021-kit-de-bandas-dominadas-x-5.png",
  },
  {
    id: 22,
    nombre: "TRX nacional",
    categoria: "Bandas",
    precio: 24000,
    unidad: null,
    imagen: "img/productos/022-trx-nacional.jpeg",
  },
  {
    id: 23,
    nombre: "Cinta de elongación",
    categoria: "Bandas",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/023-cinta-de-elongacion.jpeg",
  },
  {
    id: 24,
    nombre: "Banda con manija importada",
    categoria: "Bandas",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/024-banda-con-manija-importada.jpeg",
  },
  {
    id: 25,
    nombre: "Banda con anclaje",
    categoria: "Bandas",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/025-banda-con-anclaje.png",
  },
  {
    id: 26,
    nombre: "Pesa rusa PVC de 2 kg",
    categoria: "Pesas rusas",
    precio: 7000,
    unidad: null,
    imagen: "img/productos/026-pesa-rusa-pvc-de-2-kg.jpeg",
  },
  {
    id: 27,
    nombre: "Pesa rusa PVC de 3 kg",
    categoria: "Pesas rusas",
    precio: 7600,
    unidad: null,
    imagen: "img/productos/027-pesa-rusa-pvc-de-3-kg.jpeg",
  },
  {
    id: 28,
    nombre: "Pesa rusa PVC de 4 kg",
    categoria: "Pesas rusas",
    precio: 8600,
    unidad: null,
    imagen: "img/productos/028-pesa-rusa-pvc-de-4-kg.jpeg",
  },
  {
    id: 29,
    nombre: "Pesa rusa PVC de 5 kg",
    categoria: "Pesas rusas",
    precio: 9600,
    unidad: null,
    imagen: "img/productos/029-pesa-rusa-pvc-de-5-kg.jpeg",
  },
  {
    id: 30,
    nombre: "Pesa rusa 5 kg doble agarre",
    categoria: "Pesas rusas",
    precio: 11600,
    unidad: null,
    imagen: "img/productos/030-pesa-rusa-5-kg-doble-agarre.jpeg",
  },
  {
    id: 31,
    nombre: "Pesa rusa PVC de 6 kg",
    categoria: "Pesas rusas",
    precio: 10600,
    unidad: null,
    imagen: "img/productos/031-pesa-rusa-pvc-de-6-kg.jpeg",
  },
  {
    id: 32,
    nombre: "Pesa rusa PVC de 8 kg",
    categoria: "Pesas rusas",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/032-pesa-rusa-pvc-de-8-kg.jpeg",
  },
  {
    id: 33,
    nombre: "Pesa rusa PVC de 9 kg",
    categoria: "Pesas rusas",
    precio: 13000,
    unidad: null,
    imagen: "img/productos/033-pesa-rusa-pvc-de-9-kg.jpeg",
  },
  {
    id: 34,
    nombre: "Pesa rusa PVC de 10 kg",
    categoria: "Pesas rusas",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/034-pesa-rusa-pvc-de-10-kg.jpeg",
  },
  {
    id: 35,
    nombre: "Pesa rusa PVC de 12 kg",
    categoria: "Pesas rusas",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/035-pesa-rusa-pvc-de-12-kg.jpeg",
  },
  {
    id: 36,
    nombre: "Pesa rusa PVC de 14 kg",
    categoria: "Pesas rusas",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/036-pesa-rusa-pvc-de-14-kg.jpeg",
  },
  {
    id: 37,
    nombre: "Pesa rusa PVC de 15 kg",
    categoria: "Pesas rusas",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/037-pesa-rusa-pvc-de-15-kg.jpeg",
  },
  {
    id: 38,
    nombre: "Pesa rusa PVC de 16 kg",
    categoria: "Pesas rusas",
    precio: 32000,
    unidad: null,
    imagen: "img/productos/038-pesa-rusa-pvc-de-16-kg.jpeg",
  },
  {
    id: 39,
    nombre: "Pesa rusa recargable para discos",
    categoria: "Pesas rusas",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/039-pesa-rusa-recargable-para-discos.png",
  },
  {
    id: 40,
    nombre: "Barra hueca con topes de 1,20 cm, pintadas con pintura epoxi",
    categoria: "Barras",
    precio: 24000,
    unidad: null,
    imagen: "img/productos/040-barra-hueca-con-topes-de-1-20-cm-pintadas-con-pint.jpeg",
  },
  {
    id: 41,
    nombre: "Barra-mancuerna 1 metro",
    categoria: "Barras",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/041-barra-mancuerna-1-metro.png",
  },
  {
    id: 42,
    nombre: "Barra hueca con topes 1,50 cm, pintadas con pintura epoxi",
    categoria: "Barras",
    precio: 28000,
    unidad: null,
    imagen: "img/productos/042-barra-hueca-con-topes-1-50-cm-pintadas-con-pintura.jpeg",
  },
  {
    id: 43,
    nombre: "Barra w hueca",
    categoria: "Barras",
    precio: 40000,
    unidad: null,
    imagen: "img/productos/043-barra-w-hueca.png",
  },
  {
    id: 44,
    nombre: "Bolsa de boxeo de 0,90 cm lona brillante c/relleno",
    categoria: "Boxeo",
    precio: 48000,
    unidad: null,
    imagen: "img/productos/044-bolsa-de-boxeo-de-0-90-cm-lona-brillante-c-relleno.jpeg",
  },
  {
    id: 45,
    nombre: "Bolsa boxeo cordura con relleno",
    categoria: "Boxeo",
    precio: 42000,
    unidad: null,
    imagen: "img/productos/045-bolsa-boxeo-cordura-con-relleno.jpeg",
  },
  {
    id: 46,
    nombre: "Soporte de bolsa",
    categoria: "Boxeo",
    precio: 34000,
    unidad: null,
    imagen: "img/productos/046-soporte-de-bolsa.jpeg",
  },
  {
    id: 47,
    nombre: "Guantines de boxeo",
    categoria: "Boxeo",
    precio: 25000,
    unidad: null,
    imagen: "img/productos/047-guantines-de-boxeo.jpeg",
  },
  {
    id: 48,
    nombre: "Guantes M.M.A",
    categoria: "Boxeo",
    precio: 32000,
    unidad: null,
    imagen: "img/productos/048-guantes-m-m-a.jpeg",
  },
  {
    id: 49,
    nombre: "Guantes boxeo",
    categoria: "Boxeo",
    precio: 33000,
    unidad: null,
    imagen: "img/productos/049-guantes-boxeo.jpeg",
  },
  {
    id: 50,
    nombre: "Guantes box niño",
    categoria: "Boxeo",
    precio: 32000,
    unidad: null,
    imagen: "img/productos/050-guantes-box-nino.jpeg",
  },
  {
    id: 51,
    nombre: "Guantes foco",
    categoria: "Boxeo",
    precio: 33000,
    unidad: null,
    imagen: "img/productos/051-guantes-foco.jpeg",
  },
  {
    id: 52,
    nombre: "Bucal simple SR - JR/ adulto c/ estuche",
    categoria: "Boxeo",
    precio: 5000,
    unidad: null,
    imagen: "img/productos/052-bucal-simple-sr-jr-adulto-c-estuche.jpeg",
  },
  {
    id: 53,
    nombre: "Par de vendas 5 cm x 3 mtrs",
    categoria: "Boxeo",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/053-par-de-vendas-5-cm-x-3-mtrs.png",
  },
  {
    id: 54,
    nombre: "Vincha de reflejos de boxeo",
    categoria: "Boxeo",
    precio: 16000,
    unidad: null,
    imagen: "img/productos/054-vincha-de-reflejos-de-boxeo.jpeg",
  },
  {
    id: 55,
    nombre: "Cono de 18cm",
    categoria: "Coordinación y equilibrio",
    precio: 1800,
    unidad: null,
    imagen: "img/productos/055-cono-de-18cm.jpeg",
  },
  {
    id: 56,
    nombre: "Cono 29cm",
    categoria: "Coordinación y equilibrio",
    precio: 2200,
    unidad: null,
    imagen: "img/productos/056-cono-29cm.jpeg",
  },
  {
    id: 57,
    nombre: "Cono 38 cm ranurado",
    categoria: "Coordinación y equilibrio",
    precio: 6200,
    unidad: null,
    imagen: "img/productos/057-cono-38-cm-ranurado.jpeg",
  },
  {
    id: 58,
    nombre: "Cono ranurado 38cm x 2 + bastón de 1m",
    categoria: "Coordinación y equilibrio",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/058-cono-ranurado-38cm-x-2-baston-de-1m.jpeg",
  },
  {
    id: 59,
    nombre: "Bastón 1 metro",
    categoria: "Coordinación y equilibrio",
    precio: 2200,
    unidad: null,
    imagen: "img/productos/059-baston-1-metro.jpeg",
  },
  {
    id: 60,
    nombre: "Fleje de marcación",
    categoria: "Coordinación y equilibrio",
    precio: 650,
    unidad: null,
    imagen: "img/productos/060-fleje-de-marcacion.jpeg",
  },
  {
    id: 61,
    nombre: "Cono tortuga, colores varios",
    categoria: "Coordinación y equilibrio",
    precio: 760,
    unidad: null,
    imagen: "img/productos/061-cono-tortuga-colores-varios.jpeg",
  },
  {
    id: 62,
    nombre: "Cuadrado de coordinación 45 x 45",
    categoria: "Coordinación y equilibrio",
    precio: 5000,
    unidad: null,
    imagen: "img/productos/062-cuadrado-de-coordinacion-45-x-45.jpeg",
  },
  {
    id: 63,
    nombre: "Cuadrilátero regulable",
    categoria: "Coordinación y equilibrio",
    precio: 15000,
    unidad: null,
    imagen: "img/productos/063-cuadrilatero-regulable.jpeg",
  },
  {
    id: 64,
    nombre: "Escalera de 10 peldaños regulables",
    categoria: "Coordinación y equilibrio",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/064-escalera-de-10-peldanos-regulables.jpeg",
  },
  {
    id: 65,
    nombre: "Escalera 5 peldaños regulables",
    categoria: "Coordinación y equilibrio",
    precio: 10000,
    unidad: null,
    imagen: "img/productos/065-escalera-5-peldanos-regulables.jpeg",
  },
  {
    id: 66,
    nombre: "Valla de salto altura reg. 1 m ( 7 piezas)",
    categoria: "Coordinación y equilibrio",
    precio: 15000,
    unidad: null,
    imagen: "img/productos/066-valla-de-salto-altura-reg-1-m-7-piezas.jpeg",
  },
  {
    id: 67,
    nombre: "Tabla de equilibrio",
    categoria: "Coordinación y equilibrio",
    precio: 24000,
    unidad: null,
    imagen: "img/productos/067-tabla-de-equilibrio.jpeg",
  },
  {
    id: 68,
    nombre: "Mini bosu con pinches 15 cm",
    categoria: "Coordinación y equilibrio",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/068-mini-bosu-con-pinches-15-cm.jpeg",
  },
  {
    id: 69,
    nombre: "Mini bosu con pinches 21 cm",
    categoria: "Coordinación y equilibrio",
    precio: 21000,
    unidad: null,
    imagen: "img/productos/069-mini-bosu-con-pinches-21-cm.jpeg",
  },
  {
    id: 70,
    nombre: "Mini bosu 18 cm",
    categoria: "Coordinación y equilibrio",
    precio: 22000,
    unidad: null,
    imagen: "img/productos/070-mini-bosu-18-cm.jpeg",
  },
  {
    id: 71,
    nombre: "Medio bosu 60 cm con base y bandas",
    categoria: "Coordinación y equilibrio",
    precio: 140000,
    unidad: null,
    imagen: "img/productos/071-medio-bosu-60-cm-con-base-y-bandas.jpeg",
  },
  {
    id: 72,
    nombre: "Ula ula de 50",
    categoria: "Coordinación y equilibrio",
    precio: 2800,
    unidad: null,
    imagen: "img/productos/072-ula-ula-de-50.jpeg",
  },
  {
    id: 73,
    nombre: "Ula ula de 60",
    categoria: "Coordinación y equilibrio",
    precio: 3200,
    unidad: null,
    imagen: "img/productos/073-ula-ula-de-60.jpeg",
  },
  {
    id: 74,
    nombre: "Ula ula de 70",
    categoria: "Coordinación y equilibrio",
    precio: 3600,
    unidad: null,
    imagen: "img/productos/074-ula-ula-de-70.jpeg",
  },
  {
    id: 75,
    nombre: "Colchoneta mitad cordura mitad friselina 100 x 45 x 3cm",
    categoria: "Colchonetas y mats",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/075-colchoneta-mitad-cordura-mitad-friselina-100-x-45.jpeg",
  },
  {
    id: 76,
    nombre: "Colchoneta cordura con cierre 100 x 45 x 4cm",
    categoria: "Colchonetas y mats",
    precio: 27000,
    unidad: null,
    imagen: "img/productos/076-colchoneta-cordura-con-cierre-100-x-45-x-4cm.jpeg",
  },
  {
    id: 77,
    nombre: "Colchoneta plegable 130 x 50 x 3",
    categoria: "Colchonetas y mats",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/077-colchoneta-plegable-130-x-50-x-3.jpeg",
  },
  {
    id: 78,
    nombre: "Mat 4mm",
    categoria: "Colchonetas y mats",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/078-mat-4mm.jpeg",
  },
  {
    id: 79,
    nombre: "Mat EVA 170 x 60 x 10mm",
    categoria: "Colchonetas y mats",
    precio: 37000,
    unidad: null,
    imagen: "img/productos/079-mat-eva-170-x-60-x-10mm.jpeg",
  },
  {
    id: 80,
    nombre: "Piso de goma 100x100x 11mm",
    categoria: "Colchonetas y mats",
    precio: 36000,
    unidad: null,
    imagen: "img/productos/080-piso-de-goma-100x100x-11mm.png",
  },
  {
    id: 81,
    nombre: "Piso de goma 100x100x 23mm",
    categoria: "Colchonetas y mats",
    precio: 49000,
    unidad: null,
    imagen: "img/productos/081-piso-de-goma-100x100x-23mm.png",
  },
  {
    id: 82,
    nombre: "Corebag de 5 kg",
    categoria: "Funcional / Crossfit",
    precio: 39000,
    unidad: null,
    imagen: "img/productos/082-corebag-de-5-kg.jpeg",
  },
  {
    id: 83,
    nombre: "Corebag de 10 kg",
    categoria: "Funcional / Crossfit",
    precio: 49000,
    unidad: null,
    imagen: "img/productos/083-corebag-de-10-kg.jpeg",
  },
  {
    id: 84,
    nombre: "Corebag de 15 kg",
    categoria: "Funcional / Crossfit",
    precio: 51000,
    unidad: null,
    imagen: "img/productos/084-corebag-de-15-kg.jpeg",
  },
  {
    id: 85,
    nombre: "Corebag de 20 kg",
    categoria: "Funcional / Crossfit",
    precio: 60000,
    unidad: null,
    imagen: "img/productos/085-corebag-de-20-kg.jpeg",
  },
  {
    id: 86,
    nombre: "Pelota medicinal sin pique de 3 kg",
    categoria: "Funcional / Crossfit",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/086-pelota-medicinal-sin-pique-de-3-kg.jpeg",
  },
  {
    id: 87,
    nombre: "Pelota medicinal sin pique de 6 kg",
    categoria: "Funcional / Crossfit",
    precio: 32000,
    unidad: null,
    imagen: "img/productos/087-pelota-medicinal-sin-pique-de-6-kg.jpeg",
  },
  {
    id: 88,
    nombre: "Pelota medicinal sin pique de 9 kg",
    categoria: "Funcional / Crossfit",
    precio: 34000,
    unidad: null,
    imagen: "img/productos/088-pelota-medicinal-sin-pique-de-9-kg.jpeg",
  },
  {
    id: 89,
    nombre: "Cajón de salto 40x50x60 ( madera fenolico 20mm)",
    categoria: "Funcional / Crossfit",
    precio: 80000,
    unidad: null,
    imagen: "img/productos/089-cajon-de-salto-40x50x60-madera-fenolico-20mm.jpeg",
  },
  {
    id: 90,
    nombre: "Chaleco con peso 15 kg",
    categoria: "Funcional / Crossfit",
    precio: 60000,
    unidad: null,
    imagen: "img/productos/090-chaleco-con-peso-15-kg.jpeg",
  },
  {
    id: 91,
    nombre: "Tobillera de cuero",
    categoria: "Funcional / Crossfit",
    precio: 32000,
    unidad: null,
    imagen: "img/productos/091-tobillera-de-cuero.jpeg",
  },
  {
    id: 92,
    nombre: "Push up PVC",
    categoria: "Funcional / Crossfit",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/092-push-up-pvc.jpeg",
  },
  {
    id: 93,
    nombre: "Kit de body pump de 10 kg con barra 1,20 y topes ( 2 discos de 5 kg)",
    categoria: "Body pump y discos",
    precio: 40000,
    unidad: null,
    imagen: "img/productos/093-kit-de-body-pump-de-10-kg-con-barra-1-20-y-topes-2.jpeg",
  },
  {
    id: 94,
    nombre: "Kit body pump de 15 kg con barra 1,20 y topes (2 discos de 5 kg, 2 de 2,5 kg)",
    categoria: "Body pump y discos",
    precio: 55000,
    unidad: null,
    imagen: "img/productos/094-kit-body-pump-de-15-kg-con-barra-1-20-y-topes-2-di.jpeg",
  },
  {
    id: 95,
    nombre: "Kit body pump 18 kg con barra 1,20 y topes (2 discos de 5 kg, 2 discos de 2,5 kg, 2 discos de 1,5 kg)",
    categoria: "Body pump y discos",
    precio: 60000,
    unidad: null,
    imagen: "img/productos/095-kit-body-pump-18-kg-con-barra-1-20-y-topes-2-disco.jpeg",
  },
  {
    id: 96,
    nombre: "Kit body pump 20 kg con barra 1,20 y topes (4 discos de 5 kg)",
    categoria: "Body pump y discos",
    precio: 61000,
    unidad: null,
    imagen: "img/productos/096-kit-body-pump-20-kg-con-barra-1-20-y-topes-4-disco.jpeg",
  },
  {
    id: 97,
    nombre: "Kit body pump 30 kg con barra 1,20 y topes (6 discos de 5 kg)",
    categoria: "Body pump y discos",
    precio: 69000,
    unidad: null,
    imagen: "img/productos/097-kit-body-pump-30-kg-con-barra-1-20-y-topes-6-disco.png",
  },
  {
    id: 98,
    nombre: "Kit body 20 kg con barra 1,20 y mancuernas PVC a rosca (2 discos 5 kg, 4 discos 2,5 kg)",
    categoria: "Body pump y discos",
    precio: 75000,
    unidad: null,
    imagen: "img/productos/098-kit-body-20-kg-con-barra-1-20-y-mancuernas-pvc-a-r.jpeg",
  },
  {
    id: 99,
    nombre: "Kit body 30 kg con barra 1,20 y mancuernas PVC a rosca (4 discos de 5 kg, 4 discos de 2,5 kg)",
    categoria: "Body pump y discos",
    precio: 80000,
    unidad: null,
    imagen: "img/productos/099-kit-body-30-kg-con-barra-1-20-y-mancuernas-pvc-a-r.jpeg",
  },
  {
    id: 100,
    nombre: "Kit body 40 kg con barra 1,20 y mancuernas PVC a rosca( 6 discos 5 kg, 4 discos de 2,5)",
    categoria: "Body pump y discos",
    precio: 100000,
    unidad: null,
    imagen: "img/productos/100-kit-body-40-kg-con-barra-1-20-y-mancuernas-pvc-a-r.jpeg",
  },
  {
    id: 101,
    nombre: "Kit body 60 kg con barra de 1,50 y mancuernas de PVC a rosca ( 4 discos de 10 kg y 4 discos de",  // REVISAR: descripción cortada en el PDF original (se corta en '... y 4 discos de')
    categoria: "Body pump y discos",
    precio: 145000,
    unidad: null,
    imagen: "img/productos/101-kit-body-60-kg-con-barra-de-1-50-y-mancuernas-de-p.jpeg",
  },
  {
    id: 102,
    nombre: "Kit de mancuernas x 10 kg (2 mancuernas PVC a rosca - topes-4 discos de 2,5 kg c/agarre)",
    categoria: "Body pump y discos",
    precio: 38000,
    unidad: null,
    imagen: "img/productos/102-kit-de-mancuernas-x-10-kg-2-mancuernas-pvc-a-rosca.jpeg",
  },
  {
    id: 103,
    nombre: "Kit de mancuernas x 10 kg (2 mancuernas PVC a rosca-4 discos de 2,5 kg s/agarre)",
    categoria: "Body pump y discos",
    precio: 40000,
    unidad: null,
    imagen: "img/productos/103-kit-de-mancuernas-x-10-kg-2-mancuernas-pvc-a-rosca.jpeg",
  },
  {
    id: 104,
    nombre: "Kit liso 10 kg con barra 1,20 ( 2 discos de 5 kg)",
    categoria: "Body pump y discos",
    precio: 38000,
    unidad: null,
    imagen: "img/productos/104-kit-liso-10-kg-con-barra-1-20-2-discos-de-5-kg.jpeg",
  },
  {
    id: 105,
    nombre: "Kit liso 15 kg con barra 1,20 ( 2 discos 5 kg, 2 discos de 2,5 kg)",
    categoria: "Body pump y discos",
    precio: 44000,
    unidad: null,
    imagen: "img/productos/105-kit-liso-15-kg-con-barra-1-20-2-discos-5-kg-2-disc.png",
  },
  {
    id: 106,
    nombre: "Kit liso 17,5 kg con barra 1,20 (2 discos 5 kg, 2 discos de 2,5 kg, 2 discos de 1.25 kg)",
    categoria: "Body pump y discos",
    precio: 54000,
    unidad: null,
    imagen: "img/productos/106-kit-liso-17-5-kg-con-barra-1-20-2-discos-5-kg-2-di.jpeg",
  },
  {
    id: 107,
    nombre: "Kit liso 20 kg con barra 1,20 ( 4 discos 5 kg)",
    categoria: "Body pump y discos",
    precio: 56000,
    unidad: null,
    imagen: "img/productos/107-kit-liso-20-kg-con-barra-1-20-4-discos-5-kg.jpeg",
  },
  {
    id: 108,
    nombre: "Kit liso 30 kg con barra 1,20 (6 discos de 5 kg)",
    categoria: "Body pump y discos",
    precio: 63000,
    unidad: null,
    imagen: "img/productos/108-kit-liso-30-kg-con-barra-1-20-6-discos-de-5-kg.png",
  },
  {
    id: 109,
    nombre: "Kit de 20 kg con discos lisos (2 discos de 5 kg, 4 discos de 2,5 kg, barra 1,20 y 2 mancuernas PVC a rosca",
    categoria: "Body pump y discos",
    precio: 60000,
    unidad: null,
    imagen: "img/productos/109-kit-de-20-kg-con-discos-lisos-2-discos-de-5-kg-4-d.jpeg",
  },
  {
    id: 110,
    nombre: "Kit de 30 kg con discos lisos (4 discos de 5 kg, 4 discos de 2,5 kg, barra 1,20 c/topes, 2 mancuernas PVC a rosca)",
    categoria: "Body pump y discos",
    precio: 75000,
    unidad: null,
    imagen: "img/productos/110-kit-de-30-kg-con-discos-lisos-4-discos-de-5-kg-4-d.jpeg",
  },
  {
    id: 111,
    nombre: "Kit de 40 kg con discos lisos (6 discos de 5 kg, 4 discos de 2,5 kg, barra 1,20 c/topes, 2 mancuernas c/topes)",
    categoria: "Body pump y discos",
    precio: 82000,
    unidad: null,
    imagen: "img/productos/111-kit-de-40-kg-con-discos-lisos-6-discos-de-5-kg-4-d.jpeg",
  },
  {
    id: 112,
    nombre: "Disco con agarre PVC 1,5 kg c/u",
    categoria: "Body pump y discos",
    precio: 6100,
    unidad: "unidad",
    imagen: "img/productos/112-disco-con-agarre-pvc-1-5-kg-c-u.jpeg",
  },
  {
    id: 113,
    nombre: "Disco con agarre PVC 2,5 kg c/u",
    categoria: "Body pump y discos",
    precio: 8200,
    unidad: "unidad",
    imagen: "img/productos/113-disco-con-agarre-pvc-2-5-kg-c-u.jpeg",
  },
  {
    id: 114,
    nombre: "Disco con agarre PVC 5 kg c/u",
    categoria: "Body pump y discos",
    precio: 11000,
    unidad: "unidad",
    imagen: "img/productos/114-disco-con-agarre-pvc-5-kg-c-u.jpeg",
  },
  {
    id: 115,
    nombre: "Disco con agarre 8 kg",
    categoria: "Body pump y discos",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/115-disco-con-agarre-8-kg.jpeg",
  },
  {
    id: 116,
    nombre: "Disco c/agarre 10 kg",
    categoria: "Body pump y discos",
    precio: 24000,
    unidad: null,
    imagen: "img/productos/116-disco-c-agarre-10-kg.jpeg",
  },
  {
    id: 117,
    nombre: "Disco liso PVC 1,25 kg c/u",
    categoria: "Body pump y discos",
    precio: 5000,
    unidad: "unidad",
    imagen: "img/productos/117-disco-liso-pvc-1-25-kg-c-u.jpeg",
  },
  {
    id: 118,
    nombre: "Disco liso PVC 2,5 kg c/u",
    categoria: "Body pump y discos",
    precio: 7800,
    unidad: "unidad",
    imagen: "img/productos/118-disco-liso-pvc-2-5-kg-c-u.jpeg",
  },
  {
    id: 119,
    nombre: "Disco liso PVC 5 kg c/u",
    categoria: "Body pump y discos",
    precio: 11000,
    unidad: "unidad",
    imagen: "img/productos/119-disco-liso-pvc-5-kg-c-u.jpeg",
  },
  {
    id: 120,
    nombre: "Disco liso 12 kg",
    categoria: "Body pump y discos",
    precio: 15000,
    unidad: null,
    imagen: "img/productos/120-disco-liso-12-kg.jpeg",
  },
  {
    id: 121,
    nombre: "Topes para barra de 25mm",
    categoria: "Body pump y discos",
    precio: 2600,
    unidad: null,
    imagen: "img/productos/121-topes-para-barra-de-25mm.jpeg",
  },
  {
    id: 122,
    nombre: "Topes para barra de 28mm",
    categoria: "Body pump y discos",
    precio: 3800,
    unidad: null,
    imagen: "img/productos/122-topes-para-barra-de-28mm.jpeg",
  },
  {
    id: 123,
    nombre: "Topes para barra de 30mm",
    categoria: "Body pump y discos",
    precio: 4000,
    unidad: null,
    imagen: "img/productos/123-topes-para-barra-de-30mm.jpeg",
  },
  {
    id: 124,
    nombre: "Mancuerna recargables envase chico carga de 1/2 a 2 kg c/u",
    categoria: "Mancuernas",
    precio: 3000,
    unidad: "unidad",
    imagen: "img/productos/124-mancuerna-recargables-envase-chico-carga-de-1-2-a.jpeg",
  },
  {
    id: 125,
    nombre: "Mancuerna recargable envase grande carga de 2 a 6 kg c/u",
    categoria: "Mancuernas",
    precio: 4000,
    unidad: "unidad",
    imagen: "img/productos/125-mancuerna-recargable-envase-grande-carga-de-2-a-6.jpeg",
  },
  {
    id: 126,
    nombre: "Mancuerna de PVC a rosca (el par)",
    categoria: "Mancuernas",
    precio: 10000,
    unidad: "par",
    imagen: "img/productos/126-mancuerna-de-pvc-a-rosca-el-par.jpeg",
  },
  {
    id: 127,
    nombre: "Mancuerna PVC 1 kg c/u",
    categoria: "Mancuernas",
    precio: 4600,
    unidad: "unidad",
    imagen: "img/productos/127-mancuerna-pvc-1-kg-c-u.jpeg",
  },
  {
    id: 128,
    nombre: "Mancuerna PVC 2 kg c/u",
    categoria: "Mancuernas",
    precio: 5600,
    unidad: "unidad",
    imagen: "img/productos/128-mancuerna-pvc-2-kg-c-u.jpeg",
  },
  {
    id: 129,
    nombre: "Mancuerna PVC 3 kg c/u",
    categoria: "Mancuernas",
    precio: 7300,
    unidad: "unidad",
    imagen: "img/productos/129-mancuerna-pvc-3-kg-c-u.jpeg",
  },
  {
    id: 130,
    nombre: "Mancuerna PVC 5 kg c/u",
    categoria: "Mancuernas",
    precio: 9600,
    unidad: "unidad",
    imagen: "img/productos/130-mancuerna-pvc-5-kg-c-u.jpeg",
  },
  {
    id: 131,
    nombre: "Mancuerna 8 kg c/u",
    categoria: "Mancuernas",
    precio: 14000,
    unidad: "unidad",
    imagen: "img/productos/131-mancuerna-8-kg-c-u.jpeg",
  },
  {
    id: 132,
    nombre: "Mancuerna hueca con topes c/u",
    categoria: "Mancuernas",
    precio: 12000,
    unidad: "unidad",
    imagen: "img/productos/132-mancuerna-hueca-con-topes-c-u.jpeg",
  },
  {
    id: 133,
    nombre: "Pelota de 21cm",
    categoria: "Fitness",
    precio: 6900,
    unidad: null,
    imagen: "img/productos/133-pelota-de-21cm.jpeg",
  },
  {
    id: 134,
    nombre: "Pelota esferodinamia 55cm",
    categoria: "Fitness",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/134-pelota-esferodinamia-55cm.jpeg",
  },
  {
    id: 135,
    nombre: "Pelota esferodinamia 65 cm",
    categoria: "Fitness",
    precio: 28000,
    unidad: null,
    imagen: "img/productos/135-pelota-esferodinamia-65-cm.jpeg",
  },
  {
    id: 136,
    nombre: "Pelota esferodinamia 85cm",
    categoria: "Fitness",
    precio: 35000,
    unidad: null,
    imagen: "img/productos/136-pelota-esferodinamia-85cm.png",
  },
  {
    id: 137,
    nombre: "Inflador para esferodinamia",
    categoria: "Fitness",
    precio: 5200,
    unidad: null,
    imagen: "img/productos/137-inflador-para-esferodinamia.jpeg",
  },
  {
    id: 138,
    nombre: "Soga de PVC",
    categoria: "Fitness",
    precio: 3100,
    unidad: null,
    imagen: "img/productos/138-soga-de-pvc.jpeg",
  },
  {
    id: 139,
    nombre: "Soga de salto Speed Rope",
    categoria: "Fitness",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/139-soga-de-salto-speed-rope.jpeg",
  },
  {
    id: 140,
    nombre: "Rueda abdominal simple",
    categoria: "Fitness",
    precio: 9000,
    unidad: null,
    imagen: "img/productos/140-rueda-abdominal-simple.jpeg",
  },
  {
    id: 141,
    nombre: "Rueda abdominal doble",
    categoria: "Fitness",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/141-rueda-abdominal-doble.jpeg",
  },
  {
    id: 142,
    nombre: "Step 75 x 37 x 10",
    categoria: "Fitness",
    precio: 43000,
    unidad: null,
    imagen: "img/productos/142-step-75-x-37-x-10.jpeg",
  },
  {
    id: 143,
    nombre: "Mini step 39 x 36 x 11",
    categoria: "Fitness",
    precio: 31000,
    unidad: null,
    imagen: "img/productos/143-mini-step-39-x-36-x-11.png",
  },
  {
    id: 144,
    nombre: "Modulo para step",
    categoria: "Fitness",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/144-modulo-para-step.jpeg",
  },
  {
    id: 145,
    nombre: "Escalador con bandas",
    categoria: "Artículos",
    precio: 90000,
    unidad: null,
    imagen: "img/productos/145-escalador-con-bandas.jpeg",
  },
  {
    id: 146,
    nombre: "Cinturón de fuerza",
    categoria: "Artículos",
    precio: 31000,
    unidad: null,
    imagen: "img/productos/146-cinturon-de-fuerza.jpeg",
  },
  {
    id: 147,
    nombre: "Straps con gancho",
    categoria: "Artículos",
    precio: 35000,
    unidad: null,
    imagen: "img/productos/147-straps-con-gancho.jpeg",
  },
  {
    id: 148,
    nombre: "Llaveros gym",
    categoria: "Artículos",
    precio: 4000,
    unidad: null,
    imagen: "img/productos/148-llaveros-gym.jpeg",
  },
  {
    id: 149,
    nombre: "Cronómetro (no incluye pilas)",
    categoria: "Artículos",
    precio: 10000,
    unidad: null,
    imagen: "img/productos/149-cronometro-no-incluye-pilas.png",
  },
  {
    id: 150,
    nombre: "Spray frio, para lesiones",
    categoria: "Artículos",
    precio: 13000,
    unidad: null,
    imagen: "img/productos/150-spray-frio-para-lesiones.jpeg",
  },
  {
    id: 151,
    nombre: "Bolso de materiales (1 metro de largo de largo)",
    categoria: "Artículos",
    precio: 21000,
    unidad: null,
    imagen: "img/productos/151-bolso-de-materiales-1-metro-de-largo-de-largo.jpeg",
  },
  {
    id: 152,
    nombre: "Hand grip",
    categoria: "Artículos",
    precio: 6000,
    unidad: null,
    imagen: "img/productos/152-hand-grip.jpeg",
  },
  {
    id: 153,
    nombre: "Hand grip regulable 60 kg",
    categoria: "Artículos",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/153-hand-grip-regulable-60-kg.jpeg",
  },
  {
    id: 154,
    nombre: "Guantes de gym",
    categoria: "Artículos",
    precio: 10000,
    unidad: null,
    imagen: "img/productos/154-guantes-de-gym.jpeg",
  },
  {
    id: 155,
    nombre: "Calleras de silicona",
    categoria: "Artículos",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/155-calleras-de-silicona.jpeg",
  },
  {
    id: 156,
    nombre: "Hamaca aérea",
    categoria: "Artículos",
    precio: 40000,
    unidad: null,
    imagen: "img/productos/156-hamaca-aerea.jpeg",
  },
  {
    id: 157,
    nombre: "Bloque de yoga",
    categoria: "Artículos",
    precio: 9000,
    unidad: null,
    imagen: "img/productos/157-bloque-de-yoga.jpeg",
  },
  {
    id: 158,
    nombre: "Aro flex",
    categoria: "Artículos",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/158-aro-flex.jpeg",
  },
  {
    id: 159,
    nombre: "Pistola masajeadora 4 en 1",
    categoria: "Artículos",
    precio: 27000,
    unidad: null,
    imagen: "img/productos/159-pistola-masajeadora-4-en-1.jpeg",
  },
  {
    id: 160,
    nombre: "Rolo 33x13 cm",
    categoria: "Artículos",
    precio: 22000,
    unidad: null,
    imagen: "img/productos/160-rolo-33x13-cm.jpeg",
  },
  {
    id: 161,
    nombre: "Rolo masajeador 61 x 14 cm",
    categoria: "Artículos",
    precio: 36000,
    unidad: null,
    imagen: "img/productos/161-rolo-masajeador-61-x-14-cm.png",
  },
  {
    id: 162,
    nombre: "Minirolo 5 x 7 cm",
    categoria: "Artículos",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/162-minirolo-5-x-7-cm.png",
  },
  {
    id: 163,
    nombre: "Mini rolo 5 x 15 cm",
    categoria: "Artículos",
    precio: 13000,
    unidad: null,
    imagen: "img/productos/163-mini-rolo-5-x-15-cm.png",
  },
  {
    id: 164,
    nombre: "Mini rolo 10 x 15 cm",
    categoria: "Artículos",
    precio: 16000,
    unidad: null,
    imagen: "img/productos/164-mini-rolo-10-x-15-cm.png",
  },
  {
    id: 165,
    nombre: "Set de minirolos ( 5 x 7, 5 x 15 y 10 x 15)",
    categoria: "Artículos",
    precio: 26000,
    unidad: null,
    imagen: "img/productos/165-set-de-minirolos-5-x-7-5-x-15-y-10-x-15.png",
  },
  {
    id: 166,
    nombre: "Stick masajeador 30cm",
    categoria: "Artículos",
    precio: 17000,
    unidad: null,
    imagen: "img/productos/166-stick-masajeador-30cm.jpeg",
  },
  {
    id: 167,
    nombre: "Venda rodillera",
    categoria: "Artículos",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/167-venda-rodillera.jpeg",
  },
  {
    id: 168,
    nombre: "Riñonera Everlast",
    categoria: "Artículos",
    precio: 12000,
    unidad: null,
    imagen: "img/productos/168-rinonera-everlast.jpeg",
  },
  {
    id: 169,
    nombre: "Pelota pulpo colegial nº1",
    categoria: "Pelotas",
    precio: 14000,
    unidad: null,
    imagen: "img/productos/169-pelota-pulpo-colegial-no1.jpeg",
  },
  {
    id: 170,
    nombre: "Pelota pulpo colegial nº2",
    categoria: "Pelotas",
    precio: 15000,
    unidad: null,
    imagen: "img/productos/170-pelota-pulpo-colegial-no2.jpeg",
  },
  {
    id: 171,
    nombre: "Pechera de poliamida x10 unidades. \"TSP\" t grande",
    categoria: "Pelotas",
    precio: 55000,
    unidad: null,
    imagen: "img/productos/171-pechera-de-poliamida-x10-unidades-tsp-t-grande.jpeg",
  },
  {
    id: 172,
    nombre: "Pelota de fútbol nº5 PVC 400g",
    categoria: "Pelotas",
    precio: 36000,
    unidad: null,
    imagen: "img/productos/172-pelota-de-futbol-no5-pvc-400g.jpeg",
  },
  {
    id: 173,
    nombre: "Pelota de fútbol nº5 PVC 420g",
    categoria: "Pelotas",
    precio: 38000,
    unidad: null,
    imagen: "img/productos/173-pelota-de-futbol-no5-pvc-420g.jpeg",
  },
  {
    id: 174,
    nombre: "Pelota fútbol papi nº4 \"TSP\"",
    categoria: "Pelotas",
    precio: 47000,
    unidad: null,
    imagen: "img/productos/174-pelota-futbol-papi-no4-tsp.jpeg",
  },
  {
    id: 175,
    nombre: "Pelota fútbol nº5 Leopard Boss",
    categoria: "Pelotas",
    precio: 44000,
    unidad: null,
    imagen: "img/productos/175-pelota-futbol-no5-leopard-boss.jpeg",
  },
  {
    id: 176,
    nombre: "Pelota fútbol salon pesada PVC nº4",
    categoria: "Pelotas",
    precio: 30000,
    unidad: null,
    imagen: "img/productos/176-pelota-futbol-salon-pesada-pvc-no4.jpeg",
  },
  {
    id: 177,
    nombre: "Pelota voley pesada PVC",
    categoria: "Pelotas",
    precio: 26000,
    unidad: null,
    imagen: "img/productos/177-pelota-voley-pesada-pvc.jpeg",
  },
  {
    id: 178,
    nombre: "Pelota de voley liviana PVC",
    categoria: "Pelotas",
    precio: 17000,
    unidad: null,
    imagen: "img/productos/178-pelota-de-voley-liviana-pvc.jpeg",
  },
  {
    id: 179,
    nombre: "Pelota volleyball ecocuero v5 280g.",
    categoria: "Pelotas",
    precio: 25000,
    unidad: null,
    imagen: "img/productos/179-pelota-volleyball-ecocuero-v5-280g.jpeg",
  },
  {
    id: 180,
    nombre: "Pelota handball nº1",
    categoria: "Pelotas",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/180-pelota-handball-no1.jpeg",
  },
  {
    id: 181,
    nombre: "Pelota handball nº2",
    categoria: "Pelotas",
    precio: 20000,
    unidad: null,
    imagen: "img/productos/181-pelota-handball-no2.jpeg",
  },
  {
    id: 182,
    nombre: "Pelota básquet nº5 pesada TSP",
    categoria: "Pelotas",
    precio: 23000,
    unidad: null,
    imagen: "img/productos/182-pelota-basquet-no5-pesada-tsp.jpeg",
  },
  {
    id: 183,
    nombre: "Pelota basket, nº7 de PVC \"TSP\"",
    categoria: "Pelotas",
    precio: 21000,
    unidad: null,
    imagen: "img/productos/183-pelota-basket-no7-de-pvc-tsp.jpeg",
  },
  {
    id: 184,
    nombre: "Pelota goma espuma",
    categoria: "Pelotas",
    precio: 19000,
    unidad: null,
    imagen: "img/productos/184-pelota-goma-espuma.jpeg",
  },
  {
    id: 185,
    nombre: "Tarjetas de árbitro",
    categoria: "Pelotas",
    precio: 5500,
    unidad: null,
    imagen: "img/productos/185-tarjetas-de-arbitro.jpeg",
  },
  {
    id: 186,
    nombre: "Cinta de capitán importada",
    categoria: "Pelotas",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/186-cinta-de-capitan-importada.jpeg",
  },
  {
    id: 187,
    nombre: "Silbato Fox 40",
    categoria: "Pelotas",
    precio: 5300,
    unidad: null,
    imagen: "img/productos/187-silbato-fox-40.png",
  },
  {
    id: 188,
    nombre: "Mini inflador",
    categoria: "Pelotas",
    precio: 5700,
    unidad: null,
    imagen: "img/productos/188-mini-inflador.png",
  },
  {
    id: 189,
    nombre: "Casco niño Alpine Skate",
    categoria: "Pelotas",
    precio: 21000,
    unidad: null,
    imagen: "img/productos/189-casco-nino-alpine-skate.png",
  },
  {
    id: 190,
    nombre: "Casco smart niño importado",
    categoria: "Pelotas",
    precio: 17000,
    unidad: null,
    imagen: "img/productos/190-casco-smart-nino-importado.jpeg",
  },
  {
    id: 191,
    nombre: "Luz LED para bici",
    categoria: "Pelotas",
    precio: 5800,
    unidad: null,
    imagen: "img/productos/191-luz-led-para-bici.jpeg",
  },
  {
    id: 192,
    nombre: "Botellón 1,75 lts",
    categoria: "Otros",
    precio: 7000,
    unidad: null,
    imagen: "img/productos/192-botellon-1-75-lts.jpeg",
  },
  {
    id: 193,
    nombre: "Vaso shaker Everlast 760 ml",
    categoria: "Otros",
    precio: 18000,
    unidad: null,
    imagen: "img/productos/193-vaso-shaker-everlast-760-ml.jpeg",
  },
  {
    id: 194,
    nombre: "Mochila Discovery Camelback hermetica",
    categoria: "Otros",
    precio: 40000,
    unidad: null,
    imagen: "img/productos/194-mochila-discovery-camelback-hermetica.jpeg",
  },
  {
    id: 195,
    nombre: "Gorro natación silicona",
    categoria: "Pileta",
    precio: 7600,
    unidad: null,
    imagen: "img/productos/195-gorro-natacion-silicona.jpeg",
  },
  {
    id: 196,
    nombre: "Tablita natación chica 30x 24",
    categoria: "Pileta",
    precio: 11500,
    unidad: null,
    imagen: "img/productos/196-tablita-natacion-chica-30x-24.jpeg",
  },
  {
    id: 197,
    nombre: "Tabla natación flecha 33 x 44",
    categoria: "Pileta",
    precio: 13400,
    unidad: null,
    imagen: "img/productos/197-tabla-natacion-flecha-33-x-44.jpeg",
  },
  {
    id: 198,
    nombre: "Flota flota",
    categoria: "Pileta",
    precio: 4200,
    unidad: null,
    imagen: "img/productos/198-flota-flota.jpeg",
  },
  {
    id: 199,
    nombre: "Pullbuoy",
    categoria: "Pileta",
    precio: 5400,
    unidad: null,
    imagen: "img/productos/199-pullbuoy.jpeg",
  },
  {
    id: 200,
    nombre: "Tabla natación pullkick agarre con pullbuoy",
    categoria: "Pileta",
    precio: 8000,
    unidad: null,
    imagen: "img/productos/200-tabla-natacion-pullkick-agarre-con-pullbuoy.jpeg",
  },
  {
    id: 201,
    nombre: "Unión para flota flota c/u",
    categoria: "Pileta",
    precio: 4000,
    unidad: "unidad",
    imagen: "img/productos/201-union-para-flota-flota-c-u.jpeg",
  },
  {
    id: 202,
    nombre: "Torpedo",
    categoria: "Pileta",
    precio: 41000,
    unidad: null,
    imagen: "img/productos/202-torpedo.jpeg",
  },
  {
    id: 203,
    nombre: "Barrenador",
    categoria: "Pileta",
    precio: 38000,
    unidad: null,
    imagen: "img/productos/203-barrenador.jpeg",
  },
];
